---
- name: Print facts
  block:
    - cloudformation_facts:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        stack_name: "{{ stack_name }}"
        region: "{{ region }}"
      register: aws_facts
    - debug:
        msg: "{{ aws_facts }}"
